language: java
jdk:
  - openjdk11
os:
  - linux
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: e1fHbfYNvxTx6N0VfzkD4DCJfsNGxDXT67z4yV3F8kJ/aGIetp4XUY96671NVceM27ZmMQAqdVYQ35qagkW6sdgAfb5Q+z+JJi0N3S7P/dZrKix4hNuF9WDeOPbY6RaC+Ub6Wm9mHP+TOeC/QsipcDFnJW5aYrlPdhdmFZ+OhI4PL1Zp0rcOMPXKtYyCdfcw4akfUow318cO15scJdLuqo6HDbXMwcqZG2JqN2Jz08Av1A7XXxIWXM1T//3/CaBTNZvUnVepJgnJ+8y3P91CJkSeMoX6LDyhILg2E7sSBTwwsTekeOvQYQtIQJQ/ulPZ2EBoiv1jI2OdiTCt30yCuDowIRnfVBntPpZg0x80JaaW8p7lr53GaVAyEXyUblrhaj+ATK6JJvCP+aGfNEknDDAGHYdj0RspqJCMhmXG8YkhlF0grzi7FdZSKPA1+zuIRoN+8fwx0VdpV1sjOVN0n2sZlL/igIeZYGMCdYp02VOUFOjhPvF+qA6wdCGrbqDYHaWtHSYvS6ovz8umfNuGIxOGMqbFPjUFmvSl3MVLhIwQqp2blx3L7K/81e9RQ4n2yUd2vk5Sm67cEW67b5YaFMirRj5DgwyBM4/kpLONcmkrBPMUOJxA7Hb1obMdL0G/myMA6Kv+fj8crJfOg5Edd+N960El7brEr7KjwVDewvc=
  secret_access_key:
    secure: W4AlXTPgwgSknKSvgu4EVwyO4THryE7754oPJPwZalLrRtfHQyQrU+pdo02mxeKNlaUkFrdTmv2X4M2p0CD607TUS7T+Ch7FDwkFZZeF8n5XjvZWvhMNhtBg8/leeevK3HRTwsQuHs15uQneLQrzQbBnTOdD3Uns60Q3njLa9wJ3snMnP8+o0kUmO77NcNLeyhbytwx5i7ltr/tngDj3cCDqGweKpYUzCUdZF5rdkIE6TWgcSOdLdrP/Zr6YIjQxQnX69wP0Srt5+/mIw2jnxPg1FGQ7WH9rhd51TkciI9OlB+SaueIT4Pp+neWQr0qfnRRNTgMmy1e1wxleRWAAewgUcq0+S8JZLyFb/ZvnP3ZjB/EG9V9XCJzsR7OGTX5eq0PsUXjUr5ZLzOfXKB82BLWnqM6MDDCMMu4JJivLlzyFCzg6NaTACckhqAFZP1CrjRq+lQQbp0pCsToUWqKaFpuVnC8eg9nDEdO6pIzHMJ/KFW6r+2dDruguz3TmwowIRfxtklbilwwZKsG0JNC9PCe6sCIo2aEpGanztZH0STHS93NfeHyyOJlIx0+G0yMFxvbxondyfAtW0rPlxvheXBhLakG1K9hiuhVgs1SQgRI3aY2FI2mT70JBwDf6MLK4RYr5dFndKtBYTD+VOd2qkcX5gIj6Rr7k7EXwxgcSQho=
  region: us-east-2
  app: poc-spring-boot-demo
  env: poc-spring-boot-demo-environment
  bucket_name: poc-spring-boot-demo-bucket
